services:
  db:
    image: mysql:8.0
    container_name: culturarte_db
    environment:
      MYSQL_DATABASE: culturarte
      MYSQL_USER: culturarte
      MYSQL_PASSWORD: culturarte123
      MYSQL_ROOT_PASSWORD: culturarte123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init-db:/docker-entrypoint-initdb.d:ro



    healthcheck: #Esto hace que phpMyAdmin no intente conectarse hasta que db esté healthy. Mucho más fiable que “levantar y cruzar los dedos”.
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  app:
    build: .
    container_name: culturarte_app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DOCKER: "true"
      JWT_SECRET: ${JWT_SECRET:-aVerySecureAndLongSecretKeyThatIsAtLeast256BitsLongForHMACAlgorithms1234567890}
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/culturarte?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: culturarte
      SPRING_DATASOURCE_PASSWORD: culturarte123
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  db_data:
